%macro ClusterCountries(gap, inputvars);

/* 
 * 
 * Task code generated by SAS® Studio 5.2
 * 
 * Generated on '3/27/20, 10:04 AM'
 * Generated by 'sasdemo'
 * Generated on server 'bzlviya'
 * Generated on SAS platform 'Linux LIN X64 3.10.0-1062.9.1.el7.x86_64'
 * Generated on SAS version 'V.03.05M0P110619'
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0'
 * Generated on web client 'https://10.104.144.40/SASStudioV/main?locale=en_US&launchedFromAppSwitcher=true'
 */

ods noproctitle;
filename sfile filesrvc folderpath='/Projects/COVID-19/score' 
	filename='CLUS_pct_acc_cases_&gap..sas';
filename tempfile temp;

proc kclus data=COVID.COVID_ACC_TPD standardize=std distance=euclidean 
		noc=abc(minclusters=2) maxclusters=5 
		outstat=CASUSER.CLUS_pct_acc_cases_&gap._stats maxiter=500 seed=42;
	input &inputvars. / level=interval;
	score out=CASUSER.CLUS_pct_acc_cases_&gap._scores copyvars=(COUNTRY &inputvars.);
	code file=tempfile;
	ods output ABCStats=work._abc_stats_;
run;

%let x=%sysfunc(fcopy(tempfile, sfile));
%if &x %then %do;
%put &x - %sysfunc(sysmsg());
%end;
filename tempfile clear;
filename sfile CLEAR;

proc sgplot data=work._abc_stats_;
	vline K / response=Gap lineattrs=(thickness=5) nostatlabel;
	yaxis grid;
	label K='Number of Clusters' Gap='Gap Statistic';
run;

proc delete data=work._abc_stats_;
run;

%mend;





%let gap = 3;
%let inputvars = URBAN_POP DENSITY AVG_AGE 
				 PCT_ACC_CASES3 PCT_ACC_CASES6 PCT_ACC_CASES9
				 PCT_ACC_CASES12 PCT_ACC_CASES15 PCT_ACC_CASES18
				 PCT_ACC_CASES21 PCT_ACC_CASES24 PCT_ACC_CASES27;
%ClusterCountries(&gap., &inputvars.);

%let gap = 5;
%let inputvars = URBAN_POP DENSITY AVG_AGE 
				 PCT_ACC_CASES5 PCT_ACC_CASES10 PCT_ACC_CASES15 
				 PCT_ACC_CASES20 PCT_ACC_CASES25;
%ClusterCountries(&gap., &inputvars.);

%let gap = 6;
%let inputvars = URBAN_POP DENSITY AVG_AGE 
				 PCT_ACC_CASES6 PCT_ACC_CASES12
				 PCT_ACC_CASES18 PCT_ACC_CASES24;
%ClusterCountries(&gap., &inputvars.);

%let gap = 7;
%let inputvars = URBAN_POP DENSITY AVG_AGE 
				 PCT_ACC_CASES7 PCT_ACC_CASES14
				 PCT_ACC_CASES21 PCT_ACC_CASES28;
%ClusterCountries(&gap., &inputvars.);